
export const bookings = [
    {
      id: 'RENT-APP001',
      bookingDate: 'Karthi Rentals',
      clientName: 'Alice Johnson',
      carModel: 'BMW Motorcycle',
      carType: 'Bike',
      plan: '2 Days',
      startDate: 'Aug 1, 2028',
      endDate: 'Aug 2, 2028',
      driver: false,
      payment: '₹4,150',
      paymentStatus: 'Paid',
      status: 'Returned',
    },
    {
      id: 'RENT-APP002',
      bookingDate: 'Karthi Rentals',
      clientName: 'Bob Smith',
      carModel: 'Mercedes Benz G-Class',
      carType: 'Luxury Vehicle',
      plan: '7 Days',
      startDate: 'Aug 1, 2028',
      endDate: 'Aug 8, 2028',
      driver: true,
      payment: '₹29,050',
      paymentStatus: 'Pending',
      status: 'Ongoing',
    },
    {
      id: 'RENT-APP003',
      bookingDate: 'Karthi Rentals',
      clientName: 'Charlie Davis',
      carModel: 'Ford Transit',
      carType: 'Caravan',
      plan: '31 Days',
      startDate: 'Aug 2, 2028',
      endDate: 'Sep 2, 2028',
      driver: false,
      payment: '₹83,000',
      paymentStatus: 'Paid',
      status: 'Ongoing',
    },
    {
      id: 'RENT-APP004',
      bookingDate: 'Karthi Rentals',
      clientName: 'Diana White',
      carModel: 'Chevrolet Malibu',
      carType: 'Luxury Vehicle',
      plan: '1 Day',
      startDate: 'Aug 2, 2028',
      endDate: 'Aug 3, 2028',
      driver: true,
      payment: '₹4,150',
      paymentStatus: 'Paid',
      status: 'Returned',
    },
    {
      id: 'RENT-APP005',
      bookingDate: 'Karthi Rentals',
      clientName: 'Edward Green',
      carModel: 'Honda Civic',
      carType: 'Bike',
      plan: '8 Days',
      startDate: 'Aug 3, 2028',
      endDate: 'Aug 10, 2028',
      driver: false,
      payment: '₹29,050',
      paymentStatus: 'Pending',
      status: 'Cancelled',
    }, {
      id: 'RENT-APP006',
      bookingDate: 'Karthi Rentals',
      clientName: 'Edward Green',
      carModel: 'Honda Civic',
      carType: 'Bike',
      plan: '8 Days',
      startDate: 'Aug 3, 2028',
      endDate: 'Aug 10, 2028',
      driver: false,
      payment: '₹29,050',
      paymentStatus: 'Pending',
      status: 'Cancelled',
    }, {
      id: 'RENT-APP007',
      bookingDate: 'Karthi Rentals',
      clientName: 'Edward Green',
      carModel: 'Honda Civic',
      carType: 'Bike',
      plan: '8 Days',
      startDate: 'Aug 3, 2028',
      endDate: 'Aug 10, 2028',
      driver: false,
      payment: '₹29,050',
      paymentStatus: 'Pending',
      status: 'Cancelled',
    }, {
      id: 'RENT-APP008',
      bookingDate: 'Karthi Rentals',
      clientName: 'Edward Green',
      carModel: 'Honda Civic',
      carType: 'Bike',
      plan: '8 Days',
      startDate: 'Aug 3, 2028',
      endDate: 'Aug 10, 2028',
      driver: false,
      payment: '₹29,050',
      paymentStatus: 'Pending',
      status: 'Cancelled',
    }
  ];
  
  export const vehicleTypes = [
    { value: 'all', label: 'All Vehicle Types' },
    { value: 'bike', label: 'Bike' },
    { value: 'luxury', label: 'Luxury Vehicle' },
    { value: 'caravan', label: 'Caravan' }
  ];
  

  export const statusOptions = [
    { value: 'all', label: 'All Status' },
    { value: 'ongoing', label: 'Ongoing' },
    { value: 'returned', label: 'Returned' },
    { value: 'cancelled', label: 'Cancelled' }
  ];
  